import { Chain } from 'viem';
import {
    arbitrum,
    arbitrumNova,
    astar,
    aurora,
    avalanche,
    base,
    bsc,
    canto,
    celo,
    confluxESpace,
    coreDao,
    dfk,
    fantom,
    fuse,
    gnosis,
    kava,
    klaytn,
    mainnet,
    mantle,
    meter,
    metis,
    moonbeam,
    moonriver,
    optimism,
    polygon,
    telos,
    tenet,
} from 'viem/chains';

export class GasZipConfigData {
    public static chains: { [key: string]: { chain: Chain } } = {
        fantom: { chain: fantom },
        moonbeam: { chain: moonbeam },
        moonriver: { chain: moonriver },
        meter: { chain: meter },
        'tenet-mainnet': { chain: tenet },
        canto: { chain: canto },
        'arbitrum-nova': { chain: arbitrumNova },
        dfk: { chain: dfk },
        'kava-mainnet': { chain: kava },
        andromeda: { chain: metis },
        celo: { chain: celo },
        gnosis: { chain: gnosis },
        klaytn: { chain: klaytn },
        'cfx-espace': { chain: confluxESpace },
        fuse: { chain: fuse },
        coreDao: { chain: coreDao },
        matic: { chain: polygon },
        'astar-mainnet': { chain: astar },
        telos: { chain: telos },
        mantle: { chain: mantle },
        optimism: { chain: optimism },
        bnb: { chain: bsc },
        base: { chain: base },
        arbitrum: { chain: arbitrum },
        aurora: { chain: aurora },
        avalanche: { chain: avalanche },
    };
}
